package com.example.quizapp.models

enum class EnumCategory(val categoryNumber : Int){
    GeneralKnowledge(9),
    Books(10),
    Film(11),
    Music(12),
    MusicalAndTheaters(13),
    Television(14),
    VedioGames(15),
    BoardGames(16),
    ScienceNature(17),
    Computers(18),
    Mathematics(19),
    Mythology(20),
    Sports(21),
    Geography(22),
    History(23),
    Politics(24),
    Art(25),
    Celebrities(26),
    Animals(27),
    Vehicles(28),
    Comics(29),
    Gadgets(30),
    JapaneseAnimeAndManga(31),
    CartoonAndAnimations(32),
}